version: "3.9"
services:
  appbox:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    links:
      - postgres-db
    volumes:
      - .:/home/app
  postgres-db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=appbox
      - POSTGRES_DB=appbox
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=appboxdelivery@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=appbox
    ports:
      - "90:80"
    depends_on:
      - postgres-db
volumes:
  postgres-data:
