name: Linter & Testing

on:
  push:
    branches: [feature/ci-cd]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]

jobs:
  avoid_reduncy:
    runs-on: ubuntu-20.04
    steps:
      - name: Console Log
        run: echo "Hola Bauti"
